apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelpcamp-frontend
  # namespace: my-namespace
  labels:
    app: yelpcamp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yelpcamp-frontend
  template:
    metadata:
      labels:
        app: yelpcamp-frontend
    spec:
      containers:
        - name: yelpcamp-frontend
          image: jooankrah/yelpcamp-frontend-image
          ports:
            - containerPort: 80
